# Generated by Django 2.2.10 on 2020-06-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletags',
            name='title',
            field=models.CharField(max_length=256, null=True, verbose_name='Название'),
        ),
    ]
