# Generated by Django 2.2.10 on 2020-06-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_articletags_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletags',
            name='main',
            field=models.BooleanField(null=True),
        ),
    ]
