# Generated by Django 2.2.10 on 2020-06-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_articletags_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletags',
            name='main',
            field=models.BooleanField(null=True, verbose_name='Основной раздел'),
        ),
    ]
