# Generated by Django 2.2.10 on 2020-06-27 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200627_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articletags',
            name='title',
        ),
        migrations.AlterField(
            model_name='articletags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Tag', verbose_name='Тематический раздел'),
        ),
    ]
