# Generated by Django 2.2.10 on 2020-06-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20200627_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletags',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
