# Generated by Django 2.2.10 on 2020-06-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20200627_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.TextField(default=False, verbose_name='Тематический раздел'),
        ),
    ]
