# Generated by Django 2.2.10 on 2020-06-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20200627_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='articles',
            field=models.ManyToManyField(through='articles.ArticleTags', to='articles.Article', verbose_name='Разделы'),
        ),
    ]
