# Generated by Django 2.2.10 on 2020-06-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20200627_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletags',
            name='main',
            field=models.BooleanField(default=False, verbose_name='Основной раздел'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.TextField(null=True, verbose_name='Тематический раздел'),
        ),
    ]
